name: ci

on:
  pull_request:
    branches: '*'
  push:
    branches:
      - master
      - main
      - 'release-*'

jobs:
  mri:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        include:
          - os: macos-13
            ruby: '2.5'
          - os: macos-latest
            ruby: '3.2'
          - os: windows-latest
            ruby: '2.5'
          - os: windows-latest
            ruby: '3.2'
            
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache
      - run: bundle exec rake
        env:
          MSGPACK_DEBUG: "true"

  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # 'bundle install' and cache
      - run: sudo apt-get update && sudo apt-get install -y valgrind
      - run: bundle exec rake spec:valgrind

  other:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: ['jruby-9.3', 'jruby-9.4', 'truffleruby']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache
      - run: bundle exec rake spec
        env:
          MSGPACK_DEBUG: "true"

  head-versions:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: ['ruby-head', 'jruby-head']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache
      - run: bundle exec rake spec || echo "failed, but ignore it"
        env:
          MSGPACK_DEBUG: "true"
